/**
 * Sample pre-processed Argdown data for stories and testing
 *
 * In production, this data would be generated by @principal-ade/argdown-parser
 * on the server side and passed to the panel.
 */

import type { ArgdownMapData } from '@principal-ade/argdown-renderer';

// We need to define the types inline since they're not exported from the renderer
const ArgdownTypes = {
  EQUIVALENCE_CLASS: 'equivalence-class',
  STATEMENT: 'statement',
  ARGUMENT: 'argument',
  RELATION: 'relation',
  STATEMENT_MAP_NODE: 'statement-map-node',
  ARGUMENT_MAP_NODE: 'argument-map-node',
  GROUP_MAP_NODE: 'group-map-node',
  MAP_EDGE: 'map-edge',
} as const;

const RelationType = {
  ATTACK: 'attack',
  SUPPORT: 'support',
} as const;

/**
 * Simple debate: Should AI be regulated?
 */
export const simpleDebateData: ArgdownMapData = {
  response: {
    input: `# Should AI Be Regulated?

[AI should be regulated]: AI regulation is necessary. #speaker-a

  + <Existential Risk Argument>: AI poses risks to humanity. #speaker-a
    (1) AI systems could harm humans
    (2) Oversight prevents harmful decisions
    ----
    (3) Therefore, AI should be regulated

  - <Innovation Argument>: Regulation harms progress. #speaker-b
    (1) Technology develops too quickly
    (2) Regulation cannot keep pace
    ----
    (3) Therefore, AI should not be regulated
`,
    arguments: {
      'Existential Risk Argument': {
        type: ArgdownTypes.ARGUMENT,
        title: 'Existential Risk Argument',
        pcs: [],
        members: [],
        tags: ['speaker-a'],
        color: '#4caf50',
      },
      'Innovation Argument': {
        type: ArgdownTypes.ARGUMENT,
        title: 'Innovation Argument',
        pcs: [],
        members: [],
        tags: ['speaker-b'],
        color: '#f44336',
      },
    },
    statements: {
      'AI should be regulated': {
        type: ArgdownTypes.EQUIVALENCE_CLASS,
        title: 'AI should be regulated',
        members: [
          {
            type: ArgdownTypes.STATEMENT,
            title: 'AI should be regulated',
            text: 'AI regulation is necessary.',
            tags: ['speaker-a'],
          },
        ],
        tags: ['speaker-a'],
        color: '#2196f3',
      },
    },
    relations: [
      {
        type: ArgdownTypes.RELATION,
        from: { type: ArgdownTypes.ARGUMENT, title: 'Existential Risk Argument', pcs: [], members: [] },
        to: { type: ArgdownTypes.EQUIVALENCE_CLASS, title: 'AI should be regulated', members: [] },
        relationType: RelationType.SUPPORT,
      },
      {
        type: ArgdownTypes.RELATION,
        from: { type: ArgdownTypes.ARGUMENT, title: 'Innovation Argument', pcs: [], members: [] },
        to: { type: ArgdownTypes.EQUIVALENCE_CLASS, title: 'AI should be regulated', members: [] },
        relationType: RelationType.ATTACK,
      },
    ],
    tags: ['speaker-a', 'speaker-b'],
    map: {
      nodes: [
        {
          type: ArgdownTypes.ARGUMENT_MAP_NODE,
          id: 'Existential Risk Argument',
          title: 'Existential Risk Argument',
          labelTitle: 'Existential Risk Argument',
          labelText: 'AI poses risks to humanity.',
          color: '#4caf50',
          tags: ['speaker-a'],
        },
        {
          type: ArgdownTypes.ARGUMENT_MAP_NODE,
          id: 'Innovation Argument',
          title: 'Innovation Argument',
          labelTitle: 'Innovation Argument',
          labelText: 'Regulation harms progress.',
          color: '#f44336',
          tags: ['speaker-b'],
        },
        {
          type: ArgdownTypes.STATEMENT_MAP_NODE,
          id: 'AI should be regulated',
          title: 'AI should be regulated',
          labelTitle: 'AI should be regulated',
          labelText: 'AI regulation is necessary.',
          color: '#2196f3',
          tags: ['speaker-a'],
        },
      ],
      edges: [
        {
          type: ArgdownTypes.MAP_EDGE,
          id: 'edge-0',
          from: {
            type: ArgdownTypes.ARGUMENT_MAP_NODE,
            id: 'Existential Risk Argument',
            title: 'Existential Risk Argument',
          },
          to: {
            type: ArgdownTypes.STATEMENT_MAP_NODE,
            id: 'AI should be regulated',
            title: 'AI should be regulated',
          },
          relationType: RelationType.SUPPORT,
        },
        {
          type: ArgdownTypes.MAP_EDGE,
          id: 'edge-1',
          from: {
            type: ArgdownTypes.ARGUMENT_MAP_NODE,
            id: 'Innovation Argument',
            title: 'Innovation Argument',
          },
          to: {
            type: ArgdownTypes.STATEMENT_MAP_NODE,
            id: 'AI should be regulated',
            title: 'AI should be regulated',
          },
          relationType: RelationType.ATTACK,
        },
      ],
    },
  },
};

/**
 * Complex debate with nested arguments: Climate Policy
 */
export const complexDebateData: ArgdownMapData = {
  response: {
    input: `# Climate Policy Debate

[We should implement carbon tax]: A carbon tax is the most effective climate policy. #economist

  + <Economic Efficiency>: Market-based solutions are efficient. #economist
  - <Regressive Impact>: Carbon tax hurts the poor. #activist
    + <Revenue Recycling>: Tax revenue can offset impact. #economist
  + <Scientific Consensus>: Climate scientists support action. #scientist
  - <Economic Burden>: Tax increases costs for businesses. #business
`,
    arguments: {
      'Economic Efficiency': {
        type: ArgdownTypes.ARGUMENT,
        title: 'Economic Efficiency',
        pcs: [],
        members: [],
        tags: ['economist'],
        color: '#4caf50',
      },
      'Regressive Impact': {
        type: ArgdownTypes.ARGUMENT,
        title: 'Regressive Impact',
        pcs: [],
        members: [],
        tags: ['activist'],
        color: '#f44336',
      },
      'Revenue Recycling': {
        type: ArgdownTypes.ARGUMENT,
        title: 'Revenue Recycling',
        pcs: [],
        members: [],
        tags: ['economist'],
        color: '#8bc34a',
      },
      'Scientific Consensus': {
        type: ArgdownTypes.ARGUMENT,
        title: 'Scientific Consensus',
        pcs: [],
        members: [],
        tags: ['scientist'],
        color: '#03a9f4',
      },
      'Economic Burden': {
        type: ArgdownTypes.ARGUMENT,
        title: 'Economic Burden',
        pcs: [],
        members: [],
        tags: ['business'],
        color: '#ff9800',
      },
    },
    statements: {
      'We should implement carbon tax': {
        type: ArgdownTypes.EQUIVALENCE_CLASS,
        title: 'We should implement carbon tax',
        members: [
          {
            type: ArgdownTypes.STATEMENT,
            title: 'We should implement carbon tax',
            text: 'A carbon tax is the most effective climate policy.',
            tags: ['economist'],
          },
        ],
        tags: ['economist'],
        color: '#2196f3',
      },
    },
    relations: [
      {
        type: ArgdownTypes.RELATION,
        from: { type: ArgdownTypes.ARGUMENT, title: 'Economic Efficiency', pcs: [], members: [] },
        to: { type: ArgdownTypes.EQUIVALENCE_CLASS, title: 'We should implement carbon tax', members: [] },
        relationType: RelationType.SUPPORT,
      },
      {
        type: ArgdownTypes.RELATION,
        from: { type: ArgdownTypes.ARGUMENT, title: 'Regressive Impact', pcs: [], members: [] },
        to: { type: ArgdownTypes.EQUIVALENCE_CLASS, title: 'We should implement carbon tax', members: [] },
        relationType: RelationType.ATTACK,
      },
      {
        type: ArgdownTypes.RELATION,
        from: { type: ArgdownTypes.ARGUMENT, title: 'Revenue Recycling', pcs: [], members: [] },
        to: { type: ArgdownTypes.ARGUMENT, title: 'Regressive Impact', pcs: [], members: [] },
        relationType: RelationType.ATTACK,
      },
      {
        type: ArgdownTypes.RELATION,
        from: { type: ArgdownTypes.ARGUMENT, title: 'Scientific Consensus', pcs: [], members: [] },
        to: { type: ArgdownTypes.EQUIVALENCE_CLASS, title: 'We should implement carbon tax', members: [] },
        relationType: RelationType.SUPPORT,
      },
      {
        type: ArgdownTypes.RELATION,
        from: { type: ArgdownTypes.ARGUMENT, title: 'Economic Burden', pcs: [], members: [] },
        to: { type: ArgdownTypes.EQUIVALENCE_CLASS, title: 'We should implement carbon tax', members: [] },
        relationType: RelationType.ATTACK,
      },
    ],
    tags: ['economist', 'activist', 'scientist', 'business'],
    map: {
      nodes: [
        {
          type: ArgdownTypes.ARGUMENT_MAP_NODE,
          id: 'Economic Efficiency',
          title: 'Economic Efficiency',
          labelTitle: 'Economic Efficiency',
          labelText: 'Market-based solutions are efficient.',
          color: '#4caf50',
          tags: ['economist'],
        },
        {
          type: ArgdownTypes.ARGUMENT_MAP_NODE,
          id: 'Regressive Impact',
          title: 'Regressive Impact',
          labelTitle: 'Regressive Impact',
          labelText: 'Carbon tax hurts the poor.',
          color: '#f44336',
          tags: ['activist'],
        },
        {
          type: ArgdownTypes.ARGUMENT_MAP_NODE,
          id: 'Revenue Recycling',
          title: 'Revenue Recycling',
          labelTitle: 'Revenue Recycling',
          labelText: 'Tax revenue can offset impact.',
          color: '#8bc34a',
          tags: ['economist'],
        },
        {
          type: ArgdownTypes.ARGUMENT_MAP_NODE,
          id: 'Scientific Consensus',
          title: 'Scientific Consensus',
          labelTitle: 'Scientific Consensus',
          labelText: 'Climate scientists support action.',
          color: '#03a9f4',
          tags: ['scientist'],
        },
        {
          type: ArgdownTypes.ARGUMENT_MAP_NODE,
          id: 'Economic Burden',
          title: 'Economic Burden',
          labelTitle: 'Economic Burden',
          labelText: 'Tax increases costs for businesses.',
          color: '#ff9800',
          tags: ['business'],
        },
        {
          type: ArgdownTypes.STATEMENT_MAP_NODE,
          id: 'We should implement carbon tax',
          title: 'We should implement carbon tax',
          labelTitle: 'We should implement carbon tax',
          labelText: 'A carbon tax is the most effective climate policy.',
          color: '#2196f3',
          tags: ['economist'],
        },
      ],
      edges: [
        {
          type: ArgdownTypes.MAP_EDGE,
          id: 'edge-0',
          from: {
            type: ArgdownTypes.ARGUMENT_MAP_NODE,
            id: 'Economic Efficiency',
            title: 'Economic Efficiency',
          },
          to: {
            type: ArgdownTypes.STATEMENT_MAP_NODE,
            id: 'We should implement carbon tax',
            title: 'We should implement carbon tax',
          },
          relationType: RelationType.SUPPORT,
        },
        {
          type: ArgdownTypes.MAP_EDGE,
          id: 'edge-1',
          from: {
            type: ArgdownTypes.ARGUMENT_MAP_NODE,
            id: 'Regressive Impact',
            title: 'Regressive Impact',
          },
          to: {
            type: ArgdownTypes.STATEMENT_MAP_NODE,
            id: 'We should implement carbon tax',
            title: 'We should implement carbon tax',
          },
          relationType: RelationType.ATTACK,
        },
        {
          type: ArgdownTypes.MAP_EDGE,
          id: 'edge-2',
          from: {
            type: ArgdownTypes.ARGUMENT_MAP_NODE,
            id: 'Revenue Recycling',
            title: 'Revenue Recycling',
          },
          to: {
            type: ArgdownTypes.ARGUMENT_MAP_NODE,
            id: 'Regressive Impact',
            title: 'Regressive Impact',
          },
          relationType: RelationType.ATTACK,
        },
        {
          type: ArgdownTypes.MAP_EDGE,
          id: 'edge-3',
          from: {
            type: ArgdownTypes.ARGUMENT_MAP_NODE,
            id: 'Scientific Consensus',
            title: 'Scientific Consensus',
          },
          to: {
            type: ArgdownTypes.STATEMENT_MAP_NODE,
            id: 'We should implement carbon tax',
            title: 'We should implement carbon tax',
          },
          relationType: RelationType.SUPPORT,
        },
        {
          type: ArgdownTypes.MAP_EDGE,
          id: 'edge-4',
          from: {
            type: ArgdownTypes.ARGUMENT_MAP_NODE,
            id: 'Economic Burden',
            title: 'Economic Burden',
          },
          to: {
            type: ArgdownTypes.STATEMENT_MAP_NODE,
            id: 'We should implement carbon tax',
            title: 'We should implement carbon tax',
          },
          relationType: RelationType.ATTACK,
        },
      ],
    },
  },
};
